name: "linkcheck-action"
description: "Check links with filiph/linkcheck"
inputs:
  arguments: # id of input
    description: "Pass the linkchek arguments"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.arguments }}
